[package]
name = "tf-apply"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "tf-apply"
path = "src/main.rs"

[dependencies]
tokio.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
subtle.workspace = true
uuid.workspace = true
regex.workspace = true
chrono.workspace = true
